image:
  file: Dockerfile

ports:
  - port: 8000
  - port: 8080

tasks:
  - command:  export PATH=$PATH:/workspace/gis_utils/gis_utils_project
  - command:  git update-index --assume-unchanged .gitignore
  - command:  echo -n > .gitignore
