# Generated by Django 2.2.3 on 2019-07-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=100)),
            ],
        ),
    ]
