# Generated by Django 2.2.3 on 2019-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='s_code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
