# Generated by Django 2.2.3 on 2019-07-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0003_auto_20190730_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('s_code',)},
        ),
        migrations.AddField(
            model_name='client',
            name='audit_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
