# Generated by Django 2.2.4 on 2019-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0008_auto_20190826_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientupdatestatus',
            name='update_count',
            field=models.IntegerField(null=True),
        ),
    ]
