# Generated by Django 2.2.4 on 2019-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0011_auto_20190904_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='income',
            new_name='employee_income',
        ),
        migrations.AddField(
            model_name='client',
            name='net_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ordinary_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sales',
            field=models.IntegerField(null=True),
        ),
    ]
