# Generated by Django 2.2.4 on 2019-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0012_auto_20190904_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ave_age',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
