# Generated by Django 2.2.5 on 2019-09-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0015_auto_20190905_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='employee_income',
            new_name='income',
        ),
    ]
