# Generated by Django 2.2.5 on 2019-09-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0016_auto_20190911_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ave_age',
            new_name='average_age',
        ),
    ]
