# Generated by Django 2.2.6 on 2019-10-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0019_auto_20190928_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('title_jp', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('description_jp', models.CharField(blank=True, max_length=1000)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('url_to_image', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(null=True)),
                ('content', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
