# Generated by Django 2.2.6 on 2019-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0021_newsupdatestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published_at',)},
        ),
        migrations.AlterField(
            model_name='news',
            name='url_to_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
