# Generated by Django 2.2.7 on 2019-11-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_utils_app', '0022_auto_20191027_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAdmin',
            fields=[
                ('topic_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('serch_keyword', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('topic_id',),
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('topic_id', '-published_at')},
        ),
        migrations.AddField(
            model_name='news',
            name='topic_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
